=== MaksSkrj/epam/practice7/oldCards.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://nure.ua.skrypnyk.practice7"
            xmlns:tns="http://nure.ua.skrypnyk.practice7">

    <xsd:element name="cards">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="oldCards" type="tns:oldCards"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="oldCards">
        <xsd:sequence>
            <xsd:element name="oldCard" type="tns:oldCard" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="oldCard">
        <xsd:sequence>
            <xsd:element name="Theme" type="xsd:string"/>
            <xsd:element name="Type" type="tns:Type"/>
            <xsd:element name="Country" type="xsd:string"/>
            <xsd:element name="Year" type="xsd:positiveInteger"/>
            <xsd:element name="Author" type="xsd:string" minOccurs="0"/>
            <xsd:element name="Valuable" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Type">
        <xsd:sequence>
            <xsd:element name="TypeOfCard" type="xsd:string"/>
            <xsd:element name="isPosted" type="xsd:boolean"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== MaksSkrj/epam/practice7/oldCards.xml
<?xml version="1.0" encoding="UTF-8"?>


<st3:cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:st3="http://nure.ua.skrypnyk.practice7"
           xsi:schemaLocation="http://nure.ua.skrypnyk.practice7 oldCards.xsd">


    <oldCards>
        <oldCard>
            <Theme>Городской пейзаж</Theme>
            <Type>
                <TypeOfCard>Поздравительная</TypeOfCard>
                <isPosted>true</isPosted>
            </Type>
            <Country>Украина</Country>
            <Year>1841</Year>
            <Author>Шевченко</Author>
            <Valuable>Историческая</Valuable>
        </oldCard>

        <oldCard>
            <Theme>Природа</Theme>
            <Type>
                <TypeOfCard>Рекламная</TypeOfCard>
                <isPosted>true</isPosted>
            </Type>
            <Country>Польша</Country>
            <Year>2028</Year>
            <Valuable>Другая</Valuable>
        </oldCard>
    </oldCards>


</st3:cards>
